const express = require("express");
const router = express.Router();

const ElememtsTablaPeriodica = {
  1: {
    atomic_number: 1,
    symbol: "H",
    name: "Hidrógeno",
    category: "categoria-oTROSMETALES",
  },
  2: {
    atomic_number: 2,
    symbol: "He",
    name: "Helio",
    category: "categoria-gas-noble",
  },
  3: {
    atomic_number: 3,
    symbol: "Li",
    name: "Litio",
    category: "categoria-metal-alcalino",
  },
  4: {
    atomic_number: 4,
    symbol: "Be",
    name: "Berilio",
    category: "categoria-metal-alcalinoterreo",
  },
  5: {
    atomic_number: 5,
    symbol: "B",
    name: "Boro",
    category: "categoria-metalaloides",
  },
  6: {
    atomic_number: 6,
    symbol: "C",
    name: "Carbono",
    category: "categoria-oTROSMETALES",
  },
  7: {
    atomic_number: 7,
    symbol: "N",
    name: "Nitrógeno",
    category: "categoria-oTROSMETALES",
  },
  8: {
    atomic_number: 8,
    symbol: "O",
    name: "Oxígeno",
    category: "categoria-oTROSMETALES",
  },
  9: {
    atomic_number: 9,
    symbol: "F",
    name: "Flúor",
    category: "categoria-halogeno",
  },
  10: {
    atomic_number: 10,
    symbol: "Ne",
    name: "Neón",
    category: "categoria-gas-noble",
  },
  11: {
    atomic_number: 11,
    symbol: "Na",
    name: "Sodio",
    category: "categoria-metal-alcalino",
  },
  12: {
    atomic_number: 12,
    symbol: "Mg",
    name: "Magnesio",
    category: "categoria-metal-alcalinoterreo",
  },
  13: {
    atomic_number: 13,
    symbol: "Al",
    name: "Aluminio",
    category: "categoria-NOMETALES",
  },
  14: {
    atomic_number: 14,
    symbol: "Si",
    name: "Silicio",
    category: "categoria-metalaloides",
  },
  15: {
    atomic_number: 15,
    symbol: "P",
    name: "Fósforo",
    category: "categoria-oTROSMETALES",
  },
  16: {
    atomic_number: 16,
    symbol: "S",
    name: "Azufre",
    category: "categoria-oTROSMETALES",
  },
  17: {
    atomic_number: 17,
    symbol: "Cl",
    name: "Cloro",
    category: "categoria-halogeno",
  },
  18: {
    atomic_number: 18,
    symbol: "Ar",
    name: "Argón",
    category: "categoria-gas-noble",
  },
  19: {
    atomic_number: 19,
    symbol: "K",
    name: "Potasio",
    category: "categoria-metal-alcalino",
  },
  20: {
    atomic_number: 20,
    symbol: "Ca",
    name: "Calcio",
    category: "categoria-metal-alcalinoterreo",
  },
  21: {
    atomic_number: 21,
    symbol: "Sc",
    name: "Escandio",
    category: "categoria-metales-transicion",
  },
  22: {
    atomic_number: 22,
    symbol: "Ti",
    name: "Titanio",
    category: "categoria-metales-transicion",
  },
  23: {
    atomic_number: 23,
    symbol: "V",
    name: "Vanadio",
    category: "categoria-metales-transicion",
  },
  24: {
    atomic_number: 24,
    symbol: "Cr",
    name: "Cromo",
    category: "categoria-metales-transicion",
  },
  25: {
    atomic_number: 25,
    symbol: "Mn",
    name: "Manganeso",
    category: "categoria-metales-transicion",
  },
  26: {
    atomic_number: 26,
    symbol: "Fe",
    name: "Hierro",
    category: "categoria-metales-transicion",
  },
  27: {
    atomic_number: 27,
    symbol: "Co",
    name: "Cobalto",
    category: "categoria-metales-transicion",
  },
  28: {
    atomic_number: 28,
    symbol: "Ni",
    name: "Níquel",
    category: "categoria-metales-transicion",
  },
  29: {
    atomic_number: 29,
    symbol: "Cu",
    name: "Cobre",
    category: "categoria-metales-transicion",
  },
  30: {
    atomic_number: 30,
    symbol: "Zn",
    name: "Zinc",
    category: "categoria-metales-transicion",
  },
  31: {
    atomic_number: 31,
    symbol: "Ga",
    name: "Galio",
    category: "categoria-NOMETALES",
  },
  32: {
    atomic_number: 32,
    symbol: "Ge",
    name: "Germanio",
    category: "categoria-metalaloides",
  },
  33: {
    atomic_number: 33,
    symbol: "As",
    name: "Arsénico",
    category: "categoria-metalaloides",
  },
  34: {
    atomic_number: 34,
    symbol: "Se",
    name: "Selenio",
    category: "categoria-oTROSMETALES",
  },
  35: {
    atomic_number: 35,
    symbol: "Br",
    name: "Bromo",
    category: "categoria-halogeno",
  },
  36: {
    atomic_number: 36,
    symbol: "Kr",
    name: "Kriptón",
    category: "categoria-gas-noble",
  },
  37: {
    atomic_number: 37,
    symbol: "Rb",
    name: "Rubidio",
    category: "categoria-metal-alcalino",
  },
  38: {
    atomic_number: 38,
    symbol: "Sr",
    name: "Estroncio",
    category: "categoria-metal-alcalinoterreo",
  },
  39: {
    atomic_number: 39,
    symbol: "Y",
    name: "Itrio",
    category: "categoria-metales-transicion",
  },
  40: {
    atomic_number: 40,
    symbol: "Zr",
    name: "Circonio",
    category: "categoria-metales-transicion",
  },
  41: {
    atomic_number: 41,
    symbol: "Nb",
    name: "Niobio",
    category: "categoria-metales-transicion",
  },
  42: {
    atomic_number: 42,
    symbol: "Mo",
    name: "Molibdeno",
    category: "categoria-metales-transicion",
  },
  43: {
    atomic_number: 43,
    symbol: "Tc",
    name: "Tecnecio",
    category: "categoria-metales-transicion",
  },
  44: {
    atomic_number: 44,
    symbol: "Ru",
    name: "Rutenio",
    category: "categoria-metales-transicion",
  },
  45: {
    atomic_number: 45,
    symbol: "Rh",
    name: "Rodio",
    category: "categoria-metales-transicion",
  },
  46: {
    atomic_number: 46,
    symbol: "Pd",
    name: "Paladio",
    category: "categoria-metales-transicion",
  },
  47: {
    atomic_number: 47,
    symbol: "Ag",
    name: "Plata",
    category: "categoria-metales-transicion",
  },
  48: {
    atomic_number: 48,
    symbol: "Cd",
    name: "Cadmio",
    category: "categoria-metales-transicion",
  },
  49: {
    atomic_number: 49,
    symbol: "In",
    name: "Indio",
    category: "categoria-NOMETALES",
  },
  50: {
    atomic_number: 50,
    symbol: "Sn",
    name: "Estaño",
    category: "categoria-NOMETALES",
  },
  51: {
    atomic_number: 51,
    symbol: "Sb",
    name: "Antimonio",
    category: "categoria-metalaloides",
  },
  52: {
    atomic_number: 52,
    symbol: "Te",
    name: "Telurio",
    category: "categoria-metalaloides",
  },
  53: {
    atomic_number: 53,
    symbol: "I",
    name: "Yodo",
    category: "categoria-halogeno",
  },
  54: {
    atomic_number: 54,
    symbol: "Xe",
    name: "Xenón",
    category: "categoria-gas-noble",
  },
  55: {
    atomic_number: 55,
    symbol: "Cs",
    name: "Cesio",
    category: "categoria-metal-alcalino",
  },
  56: {
    atomic_number: 56,
    symbol: "Ba",
    name: "Bario",
    category: "categoria-metal-alcalinoterreo",
  },
  119: {
    atomic_number: "57-71",
    symbol: "La-Lu",
    name: "Lantanos",
    category: "categoria-lantanido",
  },
  57: {
    atomic_number: "57",
    symbol: "La ",
    name: "Lantano",
    category: "categoria-lantanido",
  },
  58: {
    atomic_number: 58,
    symbol: "Ce",
    name: "Cerio",
    category: "categoria-lantanido",
  },
  59: {
    atomic_number: 59,
    symbol: "Pr",
    name: "Praseodimio",
    category: "categoria-lantanido",
  },
  60: {
    atomic_number: 60,
    symbol: "Nd",
    name: "Neodimio",
    category: "categoria-lantanido",
  },
  61: {
    atomic_number: 61,
    symbol: "Pm",
    name: "Prometio",
    category: "categoria-lantanido",
  },
  62: {
    atomic_number: 62,
    symbol: "Sm",
    name: "Samario",
    category: "categoria-lantanido",
  },
  63: {
    atomic_number: 63,
    symbol: "Eu",
    name: "Europio",
    category: "categoria-lantanido",
  },
  64: {
    atomic_number: 64,
    symbol: "Gd",
    name: "Gadolinio",
    category: "categoria-lantanido",
  },
  65: {
    atomic_number: 65,
    symbol: "Tb",
    name: "Terbio",
    category: "categoria-lantanido",
  },
  66: {
    atomic_number: 66,
    symbol: "Dy",
    name: "Disprosio",
    category: "categoria-lantanido",
  },
  67: {
    atomic_number: 67,
    symbol: "Ho",
    name: "Holmio",
    category: "categoria-lantanido",
  },
  68: {
    atomic_number: 68,
    symbol: "Er",
    name: "Erbio",
    category: "categoria-lantanido",
  },
  69: {
    atomic_number: 69,
    symbol: "Tm",
    name: "Tulio",
    category: "categoria-lantanido",
  },
  70: {
    atomic_number: 70,
    symbol: "Yb",
    name: "Iterbio",
    category: "categoria-lantanido",
  },
  71: {
    atomic_number: 71,
    symbol: "Lu",
    name: "Lutecio",
    category: "categoria-lantanido",
  },
  72: {
    atomic_number: 72,
    symbol: "Hf",
    name: "Hafnio",
    category: "categoria-metales-transicion",
  },
  73: {
    atomic_number: 73,
    symbol: "Ta",
    name: "Tantalio",
    category: "categoria-metales-transicion",
  },
  74: {
    atomic_number: 74,
    symbol: "W",
    name: "Wolframio",
    category: "categoria-metales-transicion",
  },
  75: {
    atomic_number: 75,
    symbol: "Re",
    name: "Renio",
    category: "categoria-metales-transicion",
  },
  76: {
    atomic_number: 76,
    symbol: "Os",
    name: "Osmio",
    category: "categoria-metales-transicion",
  },
  77: {
    atomic_number: 77,
    symbol: "Ir",
    name: "Iridio",
    category: "categoria-metales-transicion",
  },
  78: {
    atomic_number: 78,
    symbol: "Pt",
    name: "Platino",
    category: "categoria-metales-transicion",
  },
  79: {
    atomic_number: 79,
    symbol: "Au",
    name: "Oro",
    category: "categoria-metales-transicion",
  },
  80: {
    atomic_number: 80,
    symbol: "Hg",
    name: "Mercurio",
    category: "categoria-metales-transicion",
  },
  81: {
    atomic_number: 81,
    symbol: "Tl",
    name: "Talio",
    category: "categoria-NOMETALES",
  },
  82: {
    atomic_number: 82,
    symbol: "Pb",
    name: "Plomo",
    category: "categoria-NOMETALES",
  },
  83: {
    atomic_number: 83,
    symbol: "Bi",
    name: "Bismuto",
    category: "categoria-NOMETALES",
  },
  84: {
    atomic_number: 84,
    symbol: "Po",
    name: "Polonio",
    category: "categoria-metalaloides",
  },
  85: {
    atomic_number: 85,
    symbol: "At",
    name: "Astato",
    category: "categoria-halogeno",
  },
  86: {
    atomic_number: 86,
    symbol: "Rn",
    name: "Radón",
    category: "categoria-gas-noble",
  },
  87: {
    atomic_number: 87,
    symbol: "Fr",
    name: "Francio",
    category: "categoria-metal-alcalino",
  },
  88: {
    atomic_number: 88,
    symbol: "Ra",
    name: "Radio",
    category: "categoria-metal-alcalinoterreo",
  },
  89: {
    atomic_number: "89-103",
    symbol: "Ac-Lr",
    name: "Actinio",
    category: "categoria-actinido",
  },
  120: {
    atomic_number: 89,
    symbol: "Ac",
    name: "Actinio",
    category: "categoria-actinido",
  },
  90: {
    atomic_number: 90,
    symbol: "Th",
    name: "Torio",
    category: "categoria-actinido",
  },
  91: {
    atomic_number: 91,
    symbol: "Pa",
    name: "Protactinio",
    category: "categoria-actinido",
  },
  92: {
    atomic_number: 92,
    symbol: "U",
    name: "Uranio",
    category: "categoria-actinido",
  },
  93: {
    atomic_number: 93,
    symbol: "Np",
    name: "Neptunio",
    category: "categoria-actinido",
  },
  94: {
    atomic_number: 94,
    symbol: "Pu",
    name: "Plutonio",
    category: "categoria-actinido",
  },
  95: {
    atomic_number: 95,
    symbol: "Am",
    name: "Americio",
    category: "categoria-actinido",
  },
  96: {
    atomic_number: 96,
    symbol: "Cm",
    name: "Curio",
    category: "categoria-actinido",
  },
  97: {
    atomic_number: 97,
    symbol: "Bk",
    name: "Berkelio",
    category: "categoria-actinido",
  },
  98: {
    atomic_number: 98,
    symbol: "Cf",
    name: "Californio",
    category: "categoria-actinido",
  },
  99: {
    atomic_number: 99,
    symbol: "Es",
    name: "Einstenio",
    category: "categoria-actinido",
  },
  100: {
    atomic_number: 100,
    symbol: "Fm",
    name: "Fermio",
    category: "categoria-actinido",
  },
  101: {
    atomic_number: 101,
    symbol: "Md",
    name: "Mendelevio",
    category: "categoria-actinido",
  },
  102: {
    atomic_number: 102,
    symbol: "No",
    name: "Nobelio",
    category: "categoria-actinido",
  },
  103: {
    atomic_number: 103,
    symbol: "Lr",
    name: "Lawrencio",
    category: "categoria-actinido",
  },
  104: {
    atomic_number: 104,
    symbol: "Rf",
    name: "Rutherfordio",
    category: "categoria-metales-transicion",
  },
  105: {
    atomic_number: 105,
    symbol: "Db",
    name: "Dubnio",
    category: "categoria-metales-transicion",
  },
  106: {
    atomic_number: 106,
    symbol: "Sg",
    name: "Seaborgio",
    category: "categoria-metales-transicion",
  },
  107: {
    atomic_number: 107,
    symbol: "Bh",
    name: "Bohrio",
    category: "categoria-metales-transicion",
  },
  108: {
    atomic_number: 108,
    symbol: "Hs",
    name: "Hassio",
    category: "categoria-metales-transicion",
  },
  109: {
    atomic_number: 109,
    symbol: "Mt",
    name: "Meitnerio",
    category: "categoria-metales-transicion",
  },
  110: {
    atomic_number: 110,
    symbol: "Ds",
    name: "Darmstadtio",
    category: "categoria-metales-transicion",
  },
  111: {
    atomic_number: 111,
    symbol: "Rg",
    name: "Roentgenio",
    category: "categoria-metales-transicion",
  },
  112: {
    atomic_number: 112,
    symbol: "Cn",
    name: "Copernicio",
    category: "categoria-metales-transicion",
  },
  113: {
    atomic_number: 113,
    symbol: "Nh",
    name: "Nihonio",
    category: "categoria-NOMETALES",
  },
  114: {
    atomic_number: 114,
    symbol: "Fl",
    name: "Flerovio",
    category: "categoria-NOMETALES",
  },
  115: {
    atomic_number: 115,
    symbol: "Mc",
    name: "Moscovio",
    category: "categoria-NOMETALES",
  },
  116: {
    atomic_number: 116,
    symbol: "Lv",
    name: "Livermorio",
    category: "categoria-NOMETALES",
  },
  117: {
    atomic_number: 117,
    symbol: "Ts",
    name: "Tenesino",
    category: "categoria-halogeno",
  },
  118: {
    atomic_number: 118,
    symbol: "Og",
    name: "Oganesón",
    category: "categoria-gas-noble",
  },
};

router.get("/", function (req, res, next) {
  res.render("home", {
    layaut: false,
    elementos: ElememtsTablaPeriodica,
  });
});
module.exports = router;
